name: AliasShowText
version: '${project.version}'
main: com.itsmaxymoo.aliasshowtext.AliasShowText
api-version: 1.18
authors: [ itsmaxymoo ]
description: Allow commands.yml aliases to show the user text
website: https://github.com/itsmaxymoo/AliasShowText

commands:
  aliasshowtext:
    description: "AliasShowText admin functions"
    usage: "Try subcommands: list, reload"
    permission: aliasshowtext.admin
  _showtext:
    description: ""
    usage: "Consult documentation"
  _showstring:
    description: ""
    usage: "Consult documentation"

permissions:
  aliasshowtext.admin:
    description: "Access to AliasShowText admin functions"
    default: op